In [1]:
import numpy as np
import pandas as pd
from librosa import display
import os
import librosa
import IPython.display as ipd
import glob
import sys
import matplotlib.pyplot as plt

In [2]:
path = os.getcwd()
print(path)

/home/thanuja/Downloads/multi-lang emotion data

In [3]:
Data1 = "/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/"
Data2 = "/home/thanuja/Downloads/multi-lang emotion data/output_germany/test/"

In [4]:
dir_train = os.listdir(Data1)
dir_test = os.listdir(Data2)

print(dir_train)

['Trauer(sadness)', 'Angst(fear)', 'Neutral', 'Wut(anger)', 'Langeweile(boredom)', 'freude(happiness)']

In [9]:
emotion=[]
path=[]

for sub_dir in dir_train:
    filename = os.listdir(Data1+sub_dir)
    for files in filename:
        if files[5:6]=='W':
            emotion.append('Wut')
        elif files[5:6]=='L':
            emotion.append('Langeweile')
        elif files[5:6]=='A':
            emotion.append('Angst')
        elif files[5:6]=='F':
            emotion.append('Freude')
        elif files[5:6]=='T':
            emotion.append('Trauer')
        elif files[5:6]=='N':
            emotion.append('Neutral')
        else:
            emotion.append('Error')
        path.append(Data1+sub_dir+'/'+files)

In [10]:
data_emo = pd.DataFrame(emotion,columns=['Emotion'])
data_emo.head()

  Emotion
0  Trauer
1  Trauer
2  Trauer
3  Trauer
4  Trauer

In [58]:
data_path = pd.DataFrame(path,columns=['Path'])
pd.set_option('display.max_colwidth',None)
data_path.head()

ValueError: DataFrame constructor not properly called!

In [13]:
train_data = pd.concat([data_path,data_emo],axis=1)
train_data.head()

,Path,Emotion
0,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Trauer(sadness)/08b09Tb.wav,Trauer
1,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Trauer(sadness)/11b09Td.wav,Trauer
2,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Trauer(sadness)/03b02Tb.wav,Trauer
3,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Trauer(sadness)/16a01Tb.wav,Trauer
4,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Trauer(sadness)/11a07Ta.wav,Trauer

In [14]:
train_data['Emotion'].value_counts()

Wut           101
Langeweile     64
Neutral        63
Freude         56
Angst          55
Trauer         49
Error           1
Name: Emotion, dtype: int64

In [17]:
emotion1=[]
path1=[]

for sub_dir2 in dir_test:
    filename = os.listdir(Data2+sub_dir2)
    for files in filename:
        if files[5:6]=='W':
            emotion1.append('Wut')
        elif files[5:6]=='L':
            emotion1.append('Langeweile')
        elif files[5:6]=='A':
            emotion1.append('Angst')
        elif files[5:6]=='F':
            emotion1.append('Freude')
        elif files[5:6]=='T':
            emotion1.append('Trauer')
        elif files[5:6]=='N':
            emotion1.append('Neutral')
        else:
            emotion1.append('Error')
        path1.append(Data2+sub_dir2+'/'+files)

In [18]:
data_emo_test = pd.DataFrame(emotion1,columns=['Emotion'])
data_emo_test.head()

  Emotion
0  Trauer
1  Trauer
2  Trauer
3  Trauer
4  Trauer

In [19]:
data_path1 = pd.DataFrame(path1,columns=['Path'])
pd.set_option('display.max_colwidth',None)
data_path1.head()

                                                                                              Path
0  /home/thanuja/Downloads/multi-lang emotion data/output_germany/test/Trauer(sadness)/14a02Tb.wav
1  /home/thanuja/Downloads/multi-lang emotion data/output_germany/test/Trauer(sadness)/11a02Tc.wav
2  /home/thanuja/Downloads/multi-lang emotion data/output_germany/test/Trauer(sadness)/14b02Tc.wav
3  /home/thanuja/Downloads/multi-lang emotion data/output_germany/test/Trauer(sadness)/13a05Tc.wav
4  /home/thanuja/Downloads/multi-lang emotion data/output_germany/test/Trauer(sadness)/16b03Ta.wav

In [21]:
test_data = pd.concat([data_path1,data_emo_test],axis=1)
test_data.head()

,Path,Emotion
0,/home/thanuja/Downloads/multi-lang emotion data/output_germany/test/Trauer(sadness)/14a02Tb.wav,Trauer
1,/home/thanuja/Downloads/multi-lang emotion data/output_germany/test/Trauer(sadness)/11a02Tc.wav,Trauer
2,/home/thanuja/Downloads/multi-lang emotion data/output_germany/test/Trauer(sadness)/14b02Tc.wav,Trauer
3,/home/thanuja/Downloads/multi-lang emotion data/output_germany/test/Trauer(sadness)/13a05Tc.wav,Trauer
4,/home/thanuja/Downloads/multi-lang emotion data/output_germany/test/Trauer(sadness)/16b03Ta.wav,Trauer

In [22]:
test_data['Emotion'].value_counts()

Wut           14
Neutral        9
Langeweile     9
Angst          8
Freude         8
Trauer         7
Name: Emotion, dtype: int64

In [23]:
Data=pd.concat([train_data,test_data],ignore_index=True)
Data[300:305]

,Path,Emotion
300,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Langeweile(boredom)/10a02Lb.wav,Langeweile
301,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Langeweile(boredom)/12a01Lb.wav,Langeweile
302,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Langeweile(boredom)/11b01Lb.wav,Langeweile
303,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Langeweile(boredom)/11b10Ld.wav,Langeweile
304,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Langeweile(boredom)/10b01Lb.wav,Langeweile

In [24]:
Data1= Data.reindex(np.random.permutation(Data.index))
Data1

,Path,Emotion
54,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Angst(fear)/16b01Aa.wav,Angst
368,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/freude(happiness)/11a05Fc.wav,Freude
266,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Wut(anger)/13b03Wc.wav,Wut
335,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/freude(happiness)/10b01Fa.wav,Freude
252,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Wut(anger)/12a07Wa.wav,Wut
...,...,...
30,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Trauer(sadness)/08a07Tb.wav,Trauer
391,/home/thanuja/Downloads/multi-lang emotion data/output_germany/test/Trauer(sadness)/14b02Tc.wav,Trauer
194,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Wut(anger)/13b10Wa.wav,Wut
40,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Trauer(sadness)/16b10Td.wav,Trauer
15,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Trauer(sadness)/12b03Ta.wav,Trauer

In [25]:
Data1.to_csv("Germany_Data1.csv",index=False)

In [26]:
speech_data=pd.read_csv("Germany_Data1.csv")
speech_data

,Path,Emotion
0,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Angst(fear)/16b01Aa.wav,Angst
1,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/freude(happiness)/11a05Fc.wav,Freude
2,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Wut(anger)/13b03Wc.wav,Wut
3,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/freude(happiness)/10b01Fa.wav,Freude
4,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Wut(anger)/12a07Wa.wav,Wut
...,...,...
439,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Trauer(sadness)/08a07Tb.wav,Trauer
440,/home/thanuja/Downloads/multi-lang emotion data/output_germany/test/Trauer(sadness)/14b02Tc.wav,Trauer
441,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Wut(anger)/13b10Wa.wav,Wut
442,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Trauer(sadness)/16b10Td.wav,Trauer
443,/home/thanuja/Downloads/multi-lang emotion data/output_germany/train/Trauer(sadness)/12b03Ta.wav,Trauer

In [27]:
Feature_data = pd.DataFrame(columns=['Features'])

counter = 0
for index, path in enumerate(speech_data.Path):
    X, sample_rate = librosa.load(path,res_type='kaiser_fast')
    mfccs=np.mean(librosa.feature.mfcc(y=X, sr=sample_rate,n_mfcc=40).T, axis=0)
    Feature_data.loc[counter]=[mfccs]
    counter=counter+1

In [28]:
Feature_data.head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Features
0         [-213.19186, 64.65269, -64.748604, 65.70283, -35.463882, 13.683351, -28.010393, -12.808879, -5.4227495, -20.320568, -0.76757425, -10.584791, -1.4092296, -6.87948, 5.118914, -10.046886, -2.230446, 3.7546237, -0.76695406, 9.306731, 12.036964, 12.515525, 6.35694, 13.574961, 0.5539182, -0.8381892, 2.658844, 2.545083, 7.3239036, -0.18466581, -1.84698, 0.33184078, 2.781864, 1.1799785, -0.7251505, -4.468191, 0.06309193, -1.1502293, -3.5496366, 0.6208795]
1               [-268.4606, 108.495316, -45.794533, 33.916107, -22.28638, 2.7835567, -20.260143, 1.6920218, -8.863562, -11.39826, 6.152067, -18.227625, 1.1899798, -8.107772, 0.9971906, -0.38656312, -5.9825535, -0.35372585, -4.587758, -2.2982893, -8.030226, 2.1203203, -1.5340519, 1.5343028, 7.7055044, 2.8956532, 8.177364, 8.219757, 6.331187, 6.0644073, 6.644695, 4.1821895, 4.764536, 2.7753332, 3.2307029, 3.911402, 1.1586637, 3.0419645, 0.95637953, 2.6779308]
2      [-262.5617, 100.9298, -63.110565, 13.566321, -28.686602, 5.606063, -23.35435, -9.789213, -16.198408, -16.157644, 3.2580884, -12.812263, 0.19604424, -6.4061503, 1.4974265, -11.144395, -4.80506, 3.5395904, -3.571707, 9.757155, 8.557946, 10.785821, 9.603198, 12.252287, 2.882139, -0.19586495, 1.0425556, -1.3086625, 4.9640703, -0.57136416, 0.36777136, -2.234879, -0.4164615, 2.923703, -0.25632235, -0.20111026, -0.014123378, 1.763754, 0.3068048, 0.13015752]
3  [-224.45717, 111.27647, -36.51533, 51.912174, 1.7828023, 17.393135, -17.460272, -4.9130945, -21.563026, -12.464848, 5.032176, -20.082163, 5.0051823, -4.6551347, 3.2302072, -2.8046148, -3.5973575, 0.6133146, -5.6658335, 2.2762222, -3.5953798, 5.602536, -2.6194959, -3.5805893, -0.40671968, -5.008934, -2.5021632, -4.441225, 0.16190587, -1.1055462, 1.5667052, 4.0374274, 4.400967, 3.6803193, 1.4926467, 0.5900437, -1.9078357, 0.19530585, 0.3518979, 0.85158634]
4   [-203.7294, 114.56455, -56.132637, 54.697124, -27.397905, -5.8607426, -12.88072, -1.3582468, -25.829597, -15.653159, 4.7707124, -21.691145, 6.9195876, -8.51108, 2.374582, 0.43939433, -7.755109, -0.013389412, -7.1230946, -2.2474601, -7.5219326, 1.0274713, -5.1980357, -3.5402231, -1.3387989, -7.957865, -2.579122, -3.4206111, -1.9746863, -3.8276167, 0.7621701, -0.42743367, -0.40571117, 2.328374, 0.730266, 4.6334996, 4.9149556, 7.517053, 5.959916, 4.881583]

In [29]:
Feature_data=pd.concat([pd.DataFrame(Feature_data['Features'].values.tolist()),speech_data.Emotion],axis=1)
Feature_data

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,Emotion
0,-213.191864,64.652687,-64.748604,65.702827,-35.463882,13.683351,-28.010393,-12.808879,-5.422750,-20.320568,...,0.331841,2.781864,1.179978,-0.725151,-4.468191,0.063092,-1.150229,-3.549637,0.620879,Angst
1,-268.460602,108.495316,-45.794533,33.916107,-22.286381,2.783557,-20.260143,1.692022,-8.863562,-11.398260,...,4.182189,4.764536,2.775333,3.230703,3.911402,1.158664,3.041965,0.956380,2.677931,Freude
2,-262.561707,100.929802,-63.110565,13.566321,-28.686602,5.606063,-23.354349,-9.789213,-16.198408,-16.157644,...,-2.234879,-0.416461,2.923703,-0.256322,-0.201110,-0.014123,1.763754,0.306805,0.130158,Wut
3,-224.457169,111.276466,-36.515331,51.912174,1.782802,17.393135,-17.460272,-4.913095,-21.563026,-12.464848,...,4.037427,4.400967,3.680319,1.492647,0.590044,-1.907836,0.195306,0.351898,0.851586,Freude
4,-203.729401,114.564552,-56.132637,54.697124,-27.397905,-5.860743,-12.880720,-1.358247,-25.829597,-15.653159,...,-0.427434,-0.405711,2.328374,0.730266,4.633500,4.914956,7.517053,5.959916,4.881583,Wut
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,-279.149200,94.759140,12.494661,44.602982,3.313796,27.194864,-0.005291,6.857932,6.353382,-4.615813,...,0.904394,1.579949,3.064810,2.396441,2.214152,2.573056,2.503225,3.145149,2.851524,Trauer
440,-291.463379,105.454758,-2.823214,49.237991,-7.044758,31.571493,3.993907,4.866559,2.161734,-3.573208,...,-0.128008,0.028674,2.033696,-0.379188,0.681604,-1.093243,0.232831,-0.265548,-1.456173,Trauer
441,-232.021774,108.624825,-61.517536,28.746218,-23.088058,0.490072,-18.877951,-5.723694,-17.633936,-21.257376,...,2.997897,3.401530,2.322446,1.164821,1.179254,1.512277,3.736917,2.778148,3.986041,Wut
442,-280.219025,88.648888,-22.875828,63.099369,-1.262441,18.366486,-0.105937,-0.105020,3.767666,-7.070619,...,-0.549308,-1.793177,0.164923,1.753478,2.693275,3.967311,5.380795,5.071630,6.174559,Trauer
443,-291.268066,149.168243,-9.344248,51.966255,-19.295975,14.173470,3.846642,1.264835,-4.238954,-0.081135,...,1.218079,-1.407168,0.946325,-0.305591,-0.605836,-1.508187,0.366917,-0.487803,0.030459,Trauer

In [30]:
X_data = Feature_data.drop(['Emotion'], axis=1)
X_data

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,-213.191864,64.652687,-64.748604,65.702827,-35.463882,13.683351,-28.010393,-12.808879,-5.422750,-20.320568,...,-1.846980,0.331841,2.781864,1.179978,-0.725151,-4.468191,0.063092,-1.150229,-3.549637,0.620879
1,-268.460602,108.495316,-45.794533,33.916107,-22.286381,2.783557,-20.260143,1.692022,-8.863562,-11.398260,...,6.644695,4.182189,4.764536,2.775333,3.230703,3.911402,1.158664,3.041965,0.956380,2.677931
2,-262.561707,100.929802,-63.110565,13.566321,-28.686602,5.606063,-23.354349,-9.789213,-16.198408,-16.157644,...,0.367771,-2.234879,-0.416461,2.923703,-0.256322,-0.201110,-0.014123,1.763754,0.306805,0.130158
3,-224.457169,111.276466,-36.515331,51.912174,1.782802,17.393135,-17.460272,-4.913095,-21.563026,-12.464848,...,1.566705,4.037427,4.400967,3.680319,1.492647,0.590044,-1.907836,0.195306,0.351898,0.851586
4,-203.729401,114.564552,-56.132637,54.697124,-27.397905,-5.860743,-12.880720,-1.358247,-25.829597,-15.653159,...,0.762170,-0.427434,-0.405711,2.328374,0.730266,4.633500,4.914956,7.517053,5.959916,4.881583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,-279.149200,94.759140,12.494661,44.602982,3.313796,27.194864,-0.005291,6.857932,6.353382,-4.615813,...,1.044804,0.904394,1.579949,3.064810,2.396441,2.214152,2.573056,2.503225,3.145149,2.851524
440,-291.463379,105.454758,-2.823214,49.237991,-7.044758,31.571493,3.993907,4.866559,2.161734,-3.573208,...,1.832807,-0.128008,0.028674,2.033696,-0.379188,0.681604,-1.093243,0.232831,-0.265548,-1.456173
441,-232.021774,108.624825,-61.517536,28.746218,-23.088058,0.490072,-18.877951,-5.723694,-17.633936,-21.257376,...,3.649267,2.997897,3.401530,2.322446,1.164821,1.179254,1.512277,3.736917,2.778148,3.986041
442,-280.219025,88.648888,-22.875828,63.099369,-1.262441,18.366486,-0.105937,-0.105020,3.767666,-7.070619,...,0.413949,-0.549308,-1.793177,0.164923,1.753478,2.693275,3.967311,5.380795,5.071630,6.174559
443,-291.268066,149.168243,-9.344248,51.966255,-19.295975,14.173470,3.846642,1.264835,-4.238954,-0.081135,...,0.573484,1.218079,-1.407168,0.946325,-0.305591,-0.605836,-1.508187,0.366917,-0.487803,0.030459

In [31]:
Y_data = Feature_data.Emotion
Y_data.head()

0     Angst
1    Freude
2       Wut
3    Freude
4       Wut
Name: Emotion, dtype: object

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X_data,Y_data,test_size=0.2,random_state=40)

In [43]:
from sklearn.svm import SVC
svc_model=SVC(C=100,gamma=0.00001,kernel='rbf').fit(x_train,y_train)

print('accuracy: {}'.format(svc_model.score(x_test,y_test)))

accuracy: 0.6853932584269663

In [44]:
train_acc = float(svc_model.score(x_train, y_train)*100)
print("----train accuracy score %s ----" % train_acc)

test_acc = float(svc_model.score(x_test, y_test)*100)
print("----test accuracy score %s ----" % test_acc)

----train accuracy score 89.01408450704226 ----
----test accuracy score 68.53932584269663 ----

In [51]:
from sklearn.svm import SVC
svc_model=SVC(kernel='linear').fit(x_train,y_train)

print('accuracy: {}'.format(svc_model.score(x_test,y_test)))

accuracy: 0.6853932584269663

In [52]:
train_acc = float(svc_model.score(x_train, y_train)*100)
print("----train accuracy score %s ----" % train_acc)

test_acc = float(svc_model.score(x_test, y_test)*100)
print("----test accuracy score %s ----" % test_acc)

----train accuracy score 98.59154929577466 ----
----test accuracy score 68.53932584269663 ----

In [53]:
from sklearn.svm import SVC
svc_model=SVC(C=10,gamma=0.00001,kernel='poly').fit(x_train,y_train)

print('accuracy: {}'.format(svc_model.score(x_test,y_test)))

accuracy: 0.6067415730337079

In [54]:
train_acc = float(svc_model.score(x_train, y_train)*100)
print("----train accuracy score %s ----" % train_acc)

test_acc = float(svc_model.score(x_test, y_test)*100)
print("----test accuracy score %s ----" % test_acc)

----train accuracy score 74.08450704225352 ----
----test accuracy score 60.67415730337079 ----

In [56]:
final_model_germany = SVC(C=10,gamma=0.00001,kernel='poly').fit(X_data,Y_data)

In [57]:
import pickle

pickle.dump(final_model_germany,open('germany_new.pkl','wb'))