In [1]:
import numpy as np
import pandas as pd
from librosa import display
import os
import librosa
import IPython.display as ipd
import glob
import sys
import matplotlib.pyplot as plt

In [2]:
path = os.getcwd()
print(path)

/home/thanuja/Downloads/multi-lang emotion data

In [3]:
Data1 = "/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/"
Data2 = "/home/thanuja/Downloads/multi-lang emotion data/output_Greek/test/"

In [4]:
dir_train = os.listdir(Data1)
dir_test = os.listdir(Data2)

print(dir_train)

['happiness', 'fear', 'disgust', 'sadness', 'anger']

In [6]:
emotion=[]
path=[]

for sub_dir in dir_train:
    filename = os.listdir(Data1+sub_dir)
    for files in filename:
        if files[0:1]=='a':
            emotion.append('thymomenos')
        elif files[0:1]=='d':
            emotion.append('aidia')
        elif files[0:1]=='f':
            emotion.append('fovos')
        elif files[0:1]=='h':
            emotion.append('charoumenos')
        elif files[0:1]=='s':
            emotion.append('lypimenos')
        else:
            emotion.append('Error')
        path.append(Data1+sub_dir+'/'+files)

In [7]:
data_emo = pd.DataFrame(emotion,columns=['Emotion'])
data_emo.head()

       Emotion
0  charoumenos
1  charoumenos
2  charoumenos
3  charoumenos
4  charoumenos

In [8]:
data_path = pd.DataFrame(path,columns=['Path'])
pd.set_option('display.max_colwidth',None)
data_path.head()

                                                                                       Path
0  /home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h06 (3).wav
1  /home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h07 (1).wav
2  /home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h20 (1).wav
3  /home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h13 (1).wav
4  /home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h13 (5).wav

In [9]:
train_data = pd.concat([data_path,data_emo],axis=1)
train_data.head()

,Path,Emotion
0,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h06 (3).wav,charoumenos
1,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h07 (1).wav,charoumenos
2,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h20 (1).wav,charoumenos
3,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h13 (1).wav,charoumenos
4,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h13 (5).wav,charoumenos

In [10]:
train_data['Emotion'].value_counts()

aidia          97
lypimenos      97
fovos          96
thymomenos     96
charoumenos    95
Name: Emotion, dtype: int64

In [14]:
emotion1=[]
path1=[]

for sub_dir2 in dir_test:
    filename = os.listdir(Data2+sub_dir2)
    for files in filename:
        if files[0:1]=='a':
            emotion1.append('thymomenos')
        elif files[0:1]=='d':
            emotion1.append('aidia')
        elif files[0:1]=='f':
            emotion1.append('fovos')
        elif files[0:1]=='h':
            emotion1.append('charoumenos')
        elif files[0:1]=='s':
            emotion1.append('lypimenos')
        else:
            emotion1.append('Error')
        path1.append(Data2+sub_dir2+'/'+files)

In [15]:
data_emo_test = pd.DataFrame(emotion1,columns=['Emotion'])
data_emo_test.head()

       Emotion
0  charoumenos
1  charoumenos
2  charoumenos
3  charoumenos
4  charoumenos

In [16]:
data_path1 = pd.DataFrame(path1,columns=['Path'])
pd.set_option('display.max_colwidth',None)
data_path1.head()

                                                                                      Path
0  /home/thanuja/Downloads/multi-lang emotion data/output_Greek/test/happiness/h09 (2).wav
1  /home/thanuja/Downloads/multi-lang emotion data/output_Greek/test/happiness/h14 (5).wav
2  /home/thanuja/Downloads/multi-lang emotion data/output_Greek/test/happiness/h08 (1).wav
3  /home/thanuja/Downloads/multi-lang emotion data/output_Greek/test/happiness/h08 (5).wav
4  /home/thanuja/Downloads/multi-lang emotion data/output_Greek/test/happiness/h14 (3).wav

In [17]:
test_data = pd.concat([data_path1,data_emo_test],axis=1)
test_data.head()

,Path,Emotion
0,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/test/happiness/h09 (2).wav,charoumenos
1,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/test/happiness/h14 (5).wav,charoumenos
2,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/test/happiness/h08 (1).wav,charoumenos
3,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/test/happiness/h08 (5).wav,charoumenos
4,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/test/happiness/h14 (3).wav,charoumenos

In [18]:
test_data['Emotion'].value_counts()

charoumenos    13
aidia          13
lypimenos      13
thymomenos     13
fovos          12
Name: Emotion, dtype: int64

In [19]:
Data=pd.concat([train_data,test_data],ignore_index=True)
Data[300:305]

,Path,Emotion
300,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/sadness/s06 (5).wav,lypimenos
301,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/sadness/s12 (4).wav,lypimenos
302,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/sadness/s03 (3).wav,lypimenos
303,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/sadness/s05 (5).wav,lypimenos
304,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/sadness/s18 (1).wav,lypimenos

In [22]:
Data1= Data.reindex(np.random.permutation(Data.index))
Data1

,Path,Emotion
542,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/test/anger/a17 (3).wav,thymomenos
115,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/fear/f02 (2).wav,fovos
9,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h15 (3).wav,charoumenos
156,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/fear/f10 (3).wav,fovos
215,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/disgust/d07 (3).wav,aidia
...,...,...
367,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/sadness/s16 (4).wav,lypimenos
473,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/anger/a08 (5).wav,thymomenos
112,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/fear/f11 (01).wav,fovos
30,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h20 (5).wav,charoumenos
67,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h10 (5).wav,charoumenos

In [23]:
Data1.to_csv("Greek_Data1.csv",index=False)

In [24]:
speech_data=pd.read_csv("Greek_Data1.csv")
speech_data

,Path,Emotion
0,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/test/anger/a17 (3).wav,thymomenos
1,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/fear/f02 (2).wav,fovos
2,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h15 (3).wav,charoumenos
3,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/fear/f10 (3).wav,fovos
4,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/disgust/d07 (3).wav,aidia
...,...,...
540,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/sadness/s16 (4).wav,lypimenos
541,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/anger/a08 (5).wav,thymomenos
542,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/fear/f11 (01).wav,fovos
543,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h20 (5).wav,charoumenos
544,/home/thanuja/Downloads/multi-lang emotion data/output_Greek/train/happiness/h10 (5).wav,charoumenos

In [25]:
Feature_data = pd.DataFrame(columns=['Features'])

counter = 0
for index, path in enumerate(speech_data.Path):
    X, sample_rate = librosa.load(path,res_type='kaiser_fast')
    mfccs=np.mean(librosa.feature.mfcc(y=X, sr=sample_rate,n_mfcc=40).T, axis=0)
    Feature_data.loc[counter]=[mfccs]
    counter=counter+1

In [26]:
Feature_data.head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Features
0      [-280.13446, 66.773926, -6.32041, 12.842482, -14.111846, -6.2039146, -28.100456, -4.038042, -37.252647, -11.764258, -26.53442, 0.60538936, -12.96066, -10.089658, -17.43667, -3.5619378, -14.017916, -2.4065678, -11.362044, -17.837355, -16.63502, -6.512841, -12.334211, -8.822747, -6.685264, 2.0362706, -2.8600812, 0.9065383, -2.7822192, -1.789458, -2.791779, 2.9330053, 4.0334115, -0.010653038, -2.0986722, 0.69302, -2.2150838, -3.5307436, -2.5298653, -1.0768505]
1  [-226.39844, 51.735924, -11.141307, 11.579552, -16.993662, -14.881648, -30.633297, -10.99017, -42.718235, -12.486462, -33.605907, -4.778468, -10.510477, -2.6417787, -12.261143, -11.832907, -24.146667, -7.0362043, -13.569899, 5.419445, 2.6497214, 7.5472426, 4.6019754, 8.180997, -1.3743362, 1.0562598, -2.5923092, 0.9886383, 0.67977905, 1.3149709, -0.36296627, 3.7568512, -1.9967377, 0.25145763, -2.4781125, -1.5759958, -2.5125556, -1.2597733, -1.2235491, -1.281872]
2            [-270.35458, 70.91748, -30.84786, 2.2303789, -18.966997, -9.150462, -39.16467, -7.415029, -34.14708, -11.553421, -15.487293, -6.397291, -13.435836, -2.6080232, -13.46789, -8.3805895, -10.9106245, -6.1712384, -8.339997, -10.410947, -10.174799, -3.797952, -6.9956884, -8.836147, -6.52926, -1.2341514, -2.0882008, 1.365323, -0.5672034, 3.69857, 1.4911878, -2.2409916, -1.3133234, 3.2600846, -1.3444378, 2.327681, 2.7362902, 0.8449604, -2.7070842, 0.08677081]
3      [-209.01952, 73.40202, 11.162971, 15.68662, -11.277068, 5.6793623, -32.022785, -7.4179306, -34.812454, -2.3778973, -20.314182, -0.6410194, -18.253643, 3.1746874, -16.911407, -5.3948183, -18.279306, -7.5642414, -13.282039, -6.0181975, -17.909374, -7.802196, -20.390684, -7.3911147, -9.293346, -9.297462, -14.772241, -6.4598527, -9.155107, -8.84083, -9.297457, -4.9009776, -12.374257, -3.695973, -1.5964804, -4.9054933, -4.738446, 2.0069711, 4.4595733, 5.0173645]
4           [-233.53966, 122.776764, -15.788922, 6.8481665, -7.123238, 15.399191, -25.485542, -8.179806, -16.965961, -13.520783, -0.5623127, 8.49364, -13.116395, -0.910512, -10.862082, -7.881249, -5.067479, -3.1458116, -8.309318, -8.106136, -16.85659, -10.639578, -8.661466, -6.6673694, -3.257525, 0.8028485, -5.189553, -7.216792, -10.372743, -2.019051, -4.2337675, -4.317956, -1.0069692, -2.4279175, -8.367994, -6.8354526, -2.7039413, -4.0226693, -5.7914, -5.2102137]

In [27]:
Feature_data=pd.concat([pd.DataFrame(Feature_data['Features'].values.tolist()),speech_data.Emotion],axis=1)
Feature_data

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,Emotion
0,-280.134460,66.773926,-6.320410,12.842482,-14.111846,-6.203915,-28.100456,-4.038042,-37.252647,-11.764258,...,2.933005,4.033412,-0.010653,-2.098672,0.693020,-2.215084,-3.530744,-2.529865,-1.076851,thymomenos
1,-226.398438,51.735924,-11.141307,11.579552,-16.993662,-14.881648,-30.633297,-10.990170,-42.718235,-12.486462,...,3.756851,-1.996738,0.251458,-2.478112,-1.575996,-2.512556,-1.259773,-1.223549,-1.281872,fovos
2,-270.354584,70.917480,-30.847860,2.230379,-18.966997,-9.150462,-39.164669,-7.415029,-34.147079,-11.553421,...,-2.240992,-1.313323,3.260085,-1.344438,2.327681,2.736290,0.844960,-2.707084,0.086771,charoumenos
3,-209.019516,73.402023,11.162971,15.686620,-11.277068,5.679362,-32.022785,-7.417931,-34.812454,-2.377897,...,-4.900978,-12.374257,-3.695973,-1.596480,-4.905493,-4.738446,2.006971,4.459573,5.017365,fovos
4,-233.539658,122.776764,-15.788922,6.848166,-7.123238,15.399191,-25.485542,-8.179806,-16.965961,-13.520783,...,-4.317956,-1.006969,-2.427917,-8.367994,-6.835453,-2.703941,-4.022669,-5.791400,-5.210214,aidia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,-271.851044,71.569519,11.385785,26.223391,-0.233084,4.052141,-15.656254,6.122467,-14.554915,0.634068,...,-2.957111,-5.268267,-7.358043,-4.198004,-5.710236,-7.423251,-4.834659,-1.709023,-2.643083,lypimenos
541,-281.450775,59.125595,-42.627266,23.016844,-26.186195,-5.681445,-11.486522,-6.736725,-22.098360,7.736338,...,5.275482,1.965189,-0.988293,0.017192,1.484567,-4.289590,-1.834894,1.696489,-2.130888,thymomenos
542,-275.983093,25.181549,-10.883586,32.548336,-14.620687,-0.606144,-22.284607,-17.532734,-31.899378,-4.541704,...,7.100661,3.331079,3.883517,2.040995,3.424978,3.309439,0.414987,-1.797258,0.431261,fovos
543,-281.165009,27.590239,-41.837097,11.233945,-12.971031,-6.072284,-27.467016,2.544245,-23.760483,9.169880,...,4.521058,-0.308967,0.258754,1.469562,0.061551,-0.315819,-0.531623,2.525532,-2.891518,charoumenos
544,-257.892761,51.286301,-50.678642,20.644131,-16.183495,-20.062792,-17.322563,-7.173366,-24.230316,3.542418,...,-2.260473,2.466583,1.582770,-2.459657,3.280085,-0.690954,-4.824378,-0.113124,0.091944,charoumenos

In [28]:
X_data = Feature_data.drop(['Emotion'], axis=1)
X_data

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,-280.134460,66.773926,-6.320410,12.842482,-14.111846,-6.203915,-28.100456,-4.038042,-37.252647,-11.764258,...,-2.791779,2.933005,4.033412,-0.010653,-2.098672,0.693020,-2.215084,-3.530744,-2.529865,-1.076851
1,-226.398438,51.735924,-11.141307,11.579552,-16.993662,-14.881648,-30.633297,-10.990170,-42.718235,-12.486462,...,-0.362966,3.756851,-1.996738,0.251458,-2.478112,-1.575996,-2.512556,-1.259773,-1.223549,-1.281872
2,-270.354584,70.917480,-30.847860,2.230379,-18.966997,-9.150462,-39.164669,-7.415029,-34.147079,-11.553421,...,1.491188,-2.240992,-1.313323,3.260085,-1.344438,2.327681,2.736290,0.844960,-2.707084,0.086771
3,-209.019516,73.402023,11.162971,15.686620,-11.277068,5.679362,-32.022785,-7.417931,-34.812454,-2.377897,...,-9.297457,-4.900978,-12.374257,-3.695973,-1.596480,-4.905493,-4.738446,2.006971,4.459573,5.017365
4,-233.539658,122.776764,-15.788922,6.848166,-7.123238,15.399191,-25.485542,-8.179806,-16.965961,-13.520783,...,-4.233768,-4.317956,-1.006969,-2.427917,-8.367994,-6.835453,-2.703941,-4.022669,-5.791400,-5.210214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,-271.851044,71.569519,11.385785,26.223391,-0.233084,4.052141,-15.656254,6.122467,-14.554915,0.634068,...,-5.930096,-2.957111,-5.268267,-7.358043,-4.198004,-5.710236,-7.423251,-4.834659,-1.709023,-2.643083
541,-281.450775,59.125595,-42.627266,23.016844,-26.186195,-5.681445,-11.486522,-6.736725,-22.098360,7.736338,...,-1.144702,5.275482,1.965189,-0.988293,0.017192,1.484567,-4.289590,-1.834894,1.696489,-2.130888
542,-275.983093,25.181549,-10.883586,32.548336,-14.620687,-0.606144,-22.284607,-17.532734,-31.899378,-4.541704,...,8.875467,7.100661,3.331079,3.883517,2.040995,3.424978,3.309439,0.414987,-1.797258,0.431261
543,-281.165009,27.590239,-41.837097,11.233945,-12.971031,-6.072284,-27.467016,2.544245,-23.760483,9.169880,...,-0.397758,4.521058,-0.308967,0.258754,1.469562,0.061551,-0.315819,-0.531623,2.525532,-2.891518
544,-257.892761,51.286301,-50.678642,20.644131,-16.183495,-20.062792,-17.322563,-7.173366,-24.230316,3.542418,...,-0.066593,-2.260473,2.466583,1.582770,-2.459657,3.280085,-0.690954,-4.824378,-0.113124,0.091944

In [29]:
Y_data = Feature_data.Emotion
Y_data.head()

0     thymomenos
1          fovos
2    charoumenos
3          fovos
4          aidia
Name: Emotion, dtype: object

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X_data,Y_data,test_size=0.2,random_state=40)

In [43]:
from sklearn.svm import SVC
svc_model=SVC(C=100,gamma=0.000001,kernel='rbf').fit(x_train,y_train)

print('accuracy: {}'.format(svc_model.score(x_test,y_test)))

accuracy: 0.5688073394495413

In [44]:
train_acc = float(svc_model.score(x_train, y_train)*100)
print("----train accuracy score %s ----" % train_acc)

test_acc = float(svc_model.score(x_test, y_test)*100)
print("----test accuracy score %s ----" % test_acc)

----train accuracy score 68.11926605504587 ----
----test accuracy score 56.88073394495413 ----

In [49]:
from sklearn.svm import SVC
svc_model=SVC(C=100,kernel='linear').fit(x_train,y_train)

print('accuracy: {}'.format(svc_model.score(x_test,y_test)))

accuracy: 0.6513761467889908

In [50]:
train_acc = float(svc_model.score(x_train, y_train)*100)
print("----train accuracy score %s ----" % train_acc)

test_acc = float(svc_model.score(x_test, y_test)*100)
print("----test accuracy score %s ----" % test_acc)

----train accuracy score 91.74311926605505 ----
----test accuracy score 65.13761467889908 ----

In [51]:
final_model_greek = SVC(C=100,gamma=0.000001,kernel='rbf').fit(X_data,Y_data)

In [52]:
import pickle

pickle.dump(final_model_greek,open('greek_new.pkl','wb'))