In [2]:
import numpy as np
import pandas as pd
from librosa import display
import os
import librosa
import IPython.display as ipd
import glob
import sys
import matplotlib.pyplot as plt

In [3]:
path = os.getcwd()
print(path)

/home/thanuja/Downloads/multi-lang emotion data

In [4]:
Italian_data = "/home/thanuja/Downloads/multi-lang emotion data/output_Italian/"

In [5]:
Italian_data_list = os.listdir(Italian_data)
Italian_data_list

['train', 'test', 'val']

In [6]:
Data1 = "/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/"
Data2 = "/home/thanuja/Downloads/multi-lang emotion data/output_Italian/test/"

In [7]:
dir_train = os.listdir(Data1)
dir_test = os.listdir(Data2)

print(dir_train)

['Neutra(neutral)', 'paura(fear)', 'sorpresa(surprise)', 'Rabbia(angry)', 'disgusto(disgust)', 'tristezza(sad)', 'gioia(joy)']

In [8]:
emotion=[]
path=[]

for sub_dir in dir_train:
    filename = os.listdir(Data1+sub_dir)
    for files in filename:
        part = files.split('.')[0].split('-')
        emotion.append(str(part[0]))
        path.append(Data1+sub_dir+'/'+files)

In [9]:
data_emo = pd.DataFrame(emotion,columns=['Emotion'])
data_emo.head()

  Emotion
0     neu
1     neu
2     neu
3     neu
4     neu

In [10]:
data_emo.shape

(469, 1)

In [11]:
data_emo1 = data_emo.replace({'neu':'neutra','sor':'sorpresa','pau':'paura','tri':'tristezza',
                              'gio':'gioia','rab':'rabbia','dis':'disgusto'})

In [12]:
data_emo1.head()

  Emotion
0  neutra
1  neutra
2  neutra
3  neutra
4  neutra

In [13]:
data_path = pd.DataFrame(path,columns=['Path'])
pd.set_option('display.max_colwidth',None)
data_path.head()

                                                                                                 Path
0  /home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/Neutra(neutral)/neu-m2-n5.wav
1  /home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/Neutra(neutral)/neu-m1-n5.wav
2  /home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/Neutra(neutral)/neu-m2-l3.wav
3  /home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/Neutra(neutral)/neu-m3-b3.wav
4  /home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/Neutra(neutral)/neu-m3-n5.wav

In [16]:
train_data = pd.concat([data_path,data_emo1],axis=1)
train_data.head()

,Path,Emotion
0,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/Neutra(neutral)/neu-m2-n5.wav,neutra
1,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/Neutra(neutral)/neu-m1-n5.wav,neutra
2,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/Neutra(neutral)/neu-m2-l3.wav,neutra
3,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/Neutra(neutral)/neu-m3-b3.wav,neutra
4,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/Neutra(neutral)/neu-m3-n5.wav,neutra

In [17]:
train_data['Emotion'].value_counts()

neutra       67
paura        67
sorpresa     67
rabbia       67
disgusto     67
tristezza    67
gioia        67
Name: Emotion, dtype: int64

In [22]:
emotion1=[]
path1=[]

for sub_dir2 in dir_test:
    filename = os.listdir(Data2+sub_dir2)
    for files in filename:
        part = files.split('.')[0].split('-')
        emotion1.append(str(part[0]))
        path1.append(Data2+sub_dir2+'/'+files)

In [23]:
data_emo_test = pd.DataFrame(emotion1,columns=['Emotion'])
data_emo_test.head()

  Emotion
0     neu
1     neu
2     neu
3     neu
4     neu

In [24]:
data_emo_test1 = data_emo_test.replace({'neu':'neutra','sor':'sorpresa','pau':'paura','tri':'tristezza',
                              'gio':'gioia','rab':'rabbia','dis':'disgusto'})

In [26]:
data_emo_test1.head()

  Emotion
0  neutra
1  neutra
2  neutra
3  neutra
4  neutra

In [27]:
data_emo_test1.shape

(63, 1)

In [28]:
data_path1 = pd.DataFrame(path1,columns=['Path'])
pd.set_option('display.max_colwidth',None)
data_path1.head()

                                                                                                Path
0  /home/thanuja/Downloads/multi-lang emotion data/output_Italian/test/Neutra(neutral)/neu-m1-d2.wav
1  /home/thanuja/Downloads/multi-lang emotion data/output_Italian/test/Neutra(neutral)/neu-m3-d1.wav
2  /home/thanuja/Downloads/multi-lang emotion data/output_Italian/test/Neutra(neutral)/neu-m3-d2.wav
3  /home/thanuja/Downloads/multi-lang emotion data/output_Italian/test/Neutra(neutral)/neu-m2-n4.wav
4  /home/thanuja/Downloads/multi-lang emotion data/output_Italian/test/Neutra(neutral)/neu-m3-n3.wav

In [29]:
test_data = pd.concat([data_path1,data_emo_test1],axis=1)
test_data.head()

,Path,Emotion
0,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/test/Neutra(neutral)/neu-m1-d2.wav,neutra
1,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/test/Neutra(neutral)/neu-m3-d1.wav,neutra
2,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/test/Neutra(neutral)/neu-m3-d2.wav,neutra
3,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/test/Neutra(neutral)/neu-m2-n4.wav,neutra
4,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/test/Neutra(neutral)/neu-m3-n3.wav,neutra

In [31]:
Data=pd.concat([train_data,test_data],ignore_index=True)
Data[300:305]

,Path,Emotion
300,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/disgusto(disgust)/dis-m1-d1.wav,disgusto
301,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/disgusto(disgust)/dis-m2-n1.wav,disgusto
302,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/disgusto(disgust)/dis-f3-l4.wav,disgusto
303,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/disgusto(disgust)/dis-f1-l3.wav,disgusto
304,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/disgusto(disgust)/dis-f1-n4.wav,disgusto

In [43]:
Data1= Data.reindex(np.random.permutation(Data.index))
Data1

,Path,Emotion
498,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/test/Rabbia(angry)/rab-f2-l3.wav,rabbia
23,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/Neutra(neutral)/neu-f3-l2.wav,neutra
459,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/gioia(joy)/gio-f3-l4.wav,gioia
451,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/gioia(joy)/gio-f1-d2.wav,gioia
308,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/disgusto(disgust)/dis-m3-l3.wav,disgusto
...,...,...
78,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/paura(fear)/pau-m2-n1.wav,paura
373,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/tristezza(sad)/tri-f3-l4.wav,tristezza
127,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/paura(fear)/pau-m1-n3.wav,paura
67,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/paura(fear)/pau-m2-l2.wav,paura
484,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/test/paura(fear)/pau-m1-d2.wav,paura

In [44]:
Data1.to_csv("Italian_Data1.csv",index=False)

In [45]:
speech_data=pd.read_csv("Italian_Data1.csv")
speech_data

,Path,Emotion
0,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/test/Rabbia(angry)/rab-f2-l3.wav,rabbia
1,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/Neutra(neutral)/neu-f3-l2.wav,neutra
2,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/gioia(joy)/gio-f3-l4.wav,gioia
3,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/gioia(joy)/gio-f1-d2.wav,gioia
4,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/disgusto(disgust)/dis-m3-l3.wav,disgusto
...,...,...
527,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/paura(fear)/pau-m2-n1.wav,paura
528,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/tristezza(sad)/tri-f3-l4.wav,tristezza
529,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/paura(fear)/pau-m1-n3.wav,paura
530,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/train/paura(fear)/pau-m2-l2.wav,paura
531,/home/thanuja/Downloads/multi-lang emotion data/output_Italian/test/paura(fear)/pau-m1-d2.wav,paura

In [46]:
Feature_data = pd.DataFrame(columns=['Features'])

counter = 0
for index, path in enumerate(speech_data.Path):
    X, sample_rate = librosa.load(path,res_type='kaiser_fast')
    mfccs=np.mean(librosa.feature.mfcc(y=X, sr=sample_rate,n_mfcc=40).T, axis=0)
    Feature_data.loc[counter]=[mfccs]
    counter=counter+1

In [47]:
Feature_data.head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Features
0           [-332.87598, 59.91344, -27.513355, 22.456152, -12.9084425, -7.9809413, -19.288153, 2.556841, -18.659517, -2.571778, -13.115593, 0.36834753, -9.668187, 1.7687762, -10.170032, -11.463772, -2.2583053, -6.292624, -0.03543001, 4.65539, 4.3546195, 6.8925853, 8.69643, 4.289382, 1.7130975, 6.115602, 0.669005, 6.554381, 2.7356412, 0.0527175, 1.1762033, 0.34136227, 0.9414748, -1.1233506, -1.1376526, -1.1211863, -1.7730922, 0.009069779, 1.0202764, -0.20797963]
1       [-379.58014, 104.62943, -9.591596, 32.42583, -5.4076476, -24.055714, -18.428854, 0.40657488, -14.502777, 8.277188, -13.366294, 3.4546387, -11.983557, 9.0536, -8.639742, -2.6522977, -3.2092602, -3.391487, -2.6760325, -0.40739954, -3.7671623, -3.4393423, -2.1727645, -2.9882631, -1.7320635, -2.4252374, -1.6627128, -0.85918564, -1.0508898, 0.030801322, -1.4617081, -2.8703527, 1.8443019, 4.5520415, 7.408742, 9.707396, 10.33864, 6.263563, 6.509129, 3.9688394]
2              [-456.94296, 79.06811, -14.783285, 37.25314, 2.8262293, -14.420527, -6.4605365, 0.15969545, -22.244896, 4.800382, -17.319836, 1.766201, -9.606774, 7.131066, -1.5368606, -4.351251, -5.871349, 4.1970506, -6.3405423, -5.1810074, -4.0880446, -0.14519185, 6.633905, 8.290607, 5.4604015, 5.9318237, 4.3615193, 6.251683, 6.5382886, 6.088899, 0.41034022, 0.7851333, 0.30290967, 2.847085, 1.9557145, -0.72379905, -0.29917574, -1.1823514, 1.6323569, 1.9604291]
3                 [-501.18033, 75.53184, -4.905981, 24.357649, 4.0964007, -4.978732, -6.517094, 2.8935378, 0.44850317, 2.0742085, -2.3937795, 3.3556883, -9.53687, 11.133065, -7.2031794, -0.18051384, -3.604851, 2.3921907, 0.45685863, -0.88168335, 0.018048879, 3.2316222, 2.266672, 3.525485, 4.075009, 2.718272, 7.707339, 7.4563737, 7.7358294, 5.9772005, 3.1685522, 1.6006305, -0.50807106, 2.8460133, 1.7824825, 2.4966297, 1.2078108, 1.4218367, 2.9465818, -1.4148934]
4  [-504.46008, 80.84029, 15.182596, 37.82863, -4.358944, 4.7316847, 0.123503596, 10.417257, -9.3390255, 8.242446, -12.215638, 8.731358, -5.027107, -0.3008748, 0.96713, 2.5523772, -5.3287783, 2.6200335, -5.417845, -0.5227739, -7.1388273, 0.38399866, -3.5023186, -2.072146, -0.6565366, -2.6923141, -2.5576584, -1.460122, -0.67936593, -1.3913494, -0.6807619, -0.50935024, -0.11218461, -1.0286448, -1.388685, -1.5274305, -1.3447028, -1.7078283, -2.1340568, -1.3717109]

In [48]:
Feature_data=pd.concat([pd.DataFrame(Feature_data['Features'].values.tolist()),speech_data.Emotion],axis=1)
Feature_data

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,Emotion
0,-332.875977,59.913441,-27.513355,22.456152,-12.908442,-7.980941,-19.288153,2.556841,-18.659517,-2.571778,...,0.341362,0.941475,-1.123351,-1.137653,-1.121186,-1.773092,0.009070,1.020276,-0.207980,rabbia
1,-379.580139,104.629433,-9.591596,32.425831,-5.407648,-24.055714,-18.428854,0.406575,-14.502777,8.277188,...,-2.870353,1.844302,4.552042,7.408742,9.707396,10.338640,6.263563,6.509129,3.968839,neutra
2,-456.942963,79.068108,-14.783285,37.253139,2.826229,-14.420527,-6.460536,0.159695,-22.244896,4.800382,...,0.785133,0.302910,2.847085,1.955714,-0.723799,-0.299176,-1.182351,1.632357,1.960429,gioia
3,-501.180328,75.531837,-4.905981,24.357649,4.096401,-4.978732,-6.517094,2.893538,0.448503,2.074208,...,1.600631,-0.508071,2.846013,1.782483,2.496630,1.207811,1.421837,2.946582,-1.414893,gioia
4,-504.460083,80.840286,15.182596,37.828629,-4.358944,4.731685,0.123504,10.417257,-9.339025,8.242446,...,-0.509350,-0.112185,-1.028645,-1.388685,-1.527431,-1.344703,-1.707828,-2.134057,-1.371711,disgusto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,-411.319153,85.086235,-2.406111,19.754175,7.433846,25.434124,-5.563950,7.820068,-6.512771,13.243172,...,-2.230956,0.425222,-0.648631,2.628138,-0.032002,-0.806650,-1.256288,-0.513813,0.596463,paura
528,-607.048889,80.040009,26.502209,46.658039,7.844354,12.825789,-12.302876,12.085215,-7.519782,6.588583,...,1.143047,-2.626532,0.905093,-0.368548,0.756561,-1.569524,1.016905,-2.004894,2.500691,tristezza
529,-229.328049,85.488983,-13.818852,37.006416,-1.104780,12.147435,-21.715107,-6.870841,-9.246509,-11.724942,...,-3.413030,-1.392344,-3.215308,0.020570,-0.714682,2.934404,1.791255,2.794440,2.722804,paura
530,-353.978882,87.651161,-7.130261,32.580994,18.862570,30.137575,-11.214997,3.784186,-13.781996,14.455188,...,-0.804046,-1.154799,-1.911297,-0.411673,-1.713151,-1.558733,0.550867,-0.059638,1.930863,paura
531,-375.265015,63.565342,4.087851,29.588150,0.906005,20.354258,-5.920389,3.741598,-1.907554,-3.584838,...,-0.384010,-2.275114,-3.324235,-0.727558,0.492602,0.233663,1.335043,0.172194,0.155041,paura

In [49]:
X_data = Feature_data.drop(['Emotion'], axis=1)
X_data

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,-332.875977,59.913441,-27.513355,22.456152,-12.908442,-7.980941,-19.288153,2.556841,-18.659517,-2.571778,...,1.176203,0.341362,0.941475,-1.123351,-1.137653,-1.121186,-1.773092,0.009070,1.020276,-0.207980
1,-379.580139,104.629433,-9.591596,32.425831,-5.407648,-24.055714,-18.428854,0.406575,-14.502777,8.277188,...,-1.461708,-2.870353,1.844302,4.552042,7.408742,9.707396,10.338640,6.263563,6.509129,3.968839
2,-456.942963,79.068108,-14.783285,37.253139,2.826229,-14.420527,-6.460536,0.159695,-22.244896,4.800382,...,0.410340,0.785133,0.302910,2.847085,1.955714,-0.723799,-0.299176,-1.182351,1.632357,1.960429
3,-501.180328,75.531837,-4.905981,24.357649,4.096401,-4.978732,-6.517094,2.893538,0.448503,2.074208,...,3.168552,1.600631,-0.508071,2.846013,1.782483,2.496630,1.207811,1.421837,2.946582,-1.414893
4,-504.460083,80.840286,15.182596,37.828629,-4.358944,4.731685,0.123504,10.417257,-9.339025,8.242446,...,-0.680762,-0.509350,-0.112185,-1.028645,-1.388685,-1.527431,-1.344703,-1.707828,-2.134057,-1.371711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,-411.319153,85.086235,-2.406111,19.754175,7.433846,25.434124,-5.563950,7.820068,-6.512771,13.243172,...,-1.916105,-2.230956,0.425222,-0.648631,2.628138,-0.032002,-0.806650,-1.256288,-0.513813,0.596463
528,-607.048889,80.040009,26.502209,46.658039,7.844354,12.825789,-12.302876,12.085215,-7.519782,6.588583,...,-1.584808,1.143047,-2.626532,0.905093,-0.368548,0.756561,-1.569524,1.016905,-2.004894,2.500691
529,-229.328049,85.488983,-13.818852,37.006416,-1.104780,12.147435,-21.715107,-6.870841,-9.246509,-11.724942,...,-3.787743,-3.413030,-1.392344,-3.215308,0.020570,-0.714682,2.934404,1.791255,2.794440,2.722804
530,-353.978882,87.651161,-7.130261,32.580994,18.862570,30.137575,-11.214997,3.784186,-13.781996,14.455188,...,-2.829106,-0.804046,-1.154799,-1.911297,-0.411673,-1.713151,-1.558733,0.550867,-0.059638,1.930863
531,-375.265015,63.565342,4.087851,29.588150,0.906005,20.354258,-5.920389,3.741598,-1.907554,-3.584838,...,-1.754950,-0.384010,-2.275114,-3.324235,-0.727558,0.492602,0.233663,1.335043,0.172194,0.155041

In [50]:
Y_data = Feature_data.Emotion
Y_data.head()

0      rabbia
1      neutra
2       gioia
3       gioia
4    disgusto
Name: Emotion, dtype: object

In [51]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X_data,Y_data,test_size=0.2,random_state=40)

In [96]:
from sklearn.svm import SVC
svc_model=SVC(C=100,gamma=0.00001,kernel='rbf').fit(x_train,y_train)

print('accuracy: {}'.format(svc_model.score(x_test,y_test)))

accuracy: 0.6448598130841121

In [97]:
train_acc = float(svc_model.score(x_train, y_train)*100)
print("----train accuracy score %s ----" % train_acc)

test_acc = float(svc_model.score(x_test, y_test)*100)
print("----test accuracy score %s ----" % test_acc)

----train accuracy score 86.58823529411764 ----
----test accuracy score 64.48598130841121 ----

In [114]:
from sklearn.svm import SVC
svc_model=SVC(C=10000,kernel='linear').fit(x_train,y_train)

print('accuracy: {}'.format(svc_model.score(x_test,y_test)))

accuracy: 0.5514018691588785

In [115]:
train_acc = float(svc_model.score(x_train, y_train)*100)
print("----train accuracy score %s ----" % train_acc)

test_acc = float(svc_model.score(x_test, y_test)*100)
print("----test accuracy score %s ----" % test_acc)

----train accuracy score 100.0 ----
----test accuracy score 55.140186915887845 ----

In [140]:
from sklearn.svm import SVC
svc_model=SVC(C=10,gamma=0.00001,kernel='poly').fit(x_train,y_train)

print('accuracy: {}'.format(svc_model.score(x_test,y_test)))

accuracy: 0.5420560747663551

In [141]:
train_acc = float(svc_model.score(x_train, y_train)*100)
print("----train accuracy score %s ----" % train_acc)

test_acc = float(svc_model.score(x_test, y_test)*100)
print("----test accuracy score %s ----" % test_acc)

----train accuracy score 72.0 ----
----test accuracy score 54.20560747663551 ----

In [142]:
final_model_italian = SVC(C=100,gamma=0.00001,kernel='rbf').fit(X_data,Y_data)

In [143]:
import pickle

pickle.dump(final_model_italian,open('italian_new.pkl','wb'))